version: '3.5'

services:

    mysql:
        image: mysql:${MYSQL_IMAGE_VERSION}
        restart: always
        ports:
            - ${MYSQL_PORT}:3306
        volumes:
            - "./.srv/database:/var/lib/mysql"
            - './custom.ini:/usr/local/etc/php/conf.d/custom.ini'
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    wordpress:
        build:
            context: .
            args:
                - WORDPRESS_IMAGE=${WORDPRESS_IMAGE}
        depends_on:
            - mysql
        links:
            - mysql
        ports:
            - ${WORDPRESS_PORT}:80
        restart: always
        environment:
            WORDPRESS_DB_HOST: mysql:${MYSQL_PORT}
            WORDPRESS_DB_USER: ${MYSQL_USER}
            WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
            WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
            WORDPRESS_DEBUG: ${WORDPRESS_DEBUG}
            WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
            WORDPRESS_CONFIG_EXTRA: ${WORDPRESS_CONFIG_EXTRA}
        volumes:
            - ${V_THEMES}
            - ${V_PLUGINS}
            - ${V_WORDPRESS}
            - ${V_LOG}
            - ${V_INI}